import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, Heading, Image, Skeleton, Text } from '@chakra-ui/react'
import {ApolloClient,InMemoryCache,gql} from "@apollo/client"
import {getPokemonList} from "../components/graphql"
import { useState } from 'react'
import Skeletons from '@/components/Skeleton'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })


export default function Home({pokemonList}) {

  const [data,setdata]=useState(pokemonList);
  const [loading,setloading]=useState(false);
  const [limit,setlimit]=useState(60);
  console.log(data);

  const more = async()=>{

    setloading(true);
    try{

      setlimit(limit+20)
      await getPokemonList(limit).then((res)=>{
        setdata(res);
      });
      setloading(false)
    }
    catch(err){
      setloading(false);
      console.log(err);
    }
    
}

  return (
    <>
      <Head>
        <title>Pokemon app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
     <Heading textAlign="center">Pokemon App</Heading>
           
           <Box display="grid" gridTemplateColumns="repeat(4,1fr)"p={4} gap="20px" justifyContent="space-between">

      {
        data.map((el)=>
        <Link key={el.id} href={`/${el.id}`}><Box  p={5} border="1px solid goldenrod" borderRadius="20px">
          <Image width="100%" height="250px" src={el.image}/>
          <Text color="grey" fontWeight="bold">#{el.number}</Text>
          <Text fontWeight="bold" fontSize="2xl">{el.name}</Text>

          <Box display="flex" gap="20px">
            {el.types.map((type,i)=>
            <Button backgroundColor="blue.100" p={1} key={i} height="-webkit-fit-content">{type}</Button>
            )}
          </Box>
        </Box>
        </Link>
        )
      }
           </Box>
            {loading && <Skeletons/>}
          <Box  p={4} textAlign="center"><Button backgroundColor="goldenrod" onClick={more}>load more</Button></Box> 


    </>
  )
}


export async function getStaticProps() {
  const pokemonList = await getPokemonList(60);

  return {
    props: {
      pokemonList,
    },
  };
}